import os
i = int(input())
path = "D:/algorithm/LeetCode/offer/" + str(i)
os.mkdir(path)
f = open(path + "/" + str(i) + ".cpp", "w")
f.write("#include <bits/stdc++.h>\n")
f.write("using namespace std;\n")
f.write("class Solution {\n")
f.write("\n")
f.write("};\n")
f.write("int main() {\n")
f.write("    \n")
f.write("    Solution solution;\n")
f.write("    \n")
f.write("    return 0;\n")
f.write("}\n")
f.close()
i += 1;